package redisx

import (
	"github.com/gomodule/redigo/redisx"
	"github.com/gomodule/redigo/v2/redis"
)

// generated by goforward github.com/arnottcr/redigo/redisx github.com/gomodule/redigo/v2/redisx

// ConnMux multiplexes one or more connections to a single underlying
// connection. The ConnMux connections do not support concurrency, commands
// that associate server side state with the connection or commands that put
// the connection in a special mode.
type ConnMux = redisx.ConnMux

func NewConnMux(c redis.Conn) *ConnMux {
	return redisx.NewConnMux(c)
}
